DROP TABLE IF EXISTS PS_PERSONAL_PHONE;
CREATE TABLE PS_PERSONAL_PHONE (
    EMPLID          VARCHAR(11) NOT NULL,
    PHONE_TYPE      VARCHAR(4) NOT NULL,
    COUNTRY_CODE    VARCHAR(3) NOT NULL,
    PHONE           VARCHAR(24) NOT NULL,
    EXTENSION       VARCHAR(6) NOT NULL,
    PREF_PHONE_FLAG VARCHAR(1) NOT NULL
);
