DROP TABLE IF EXISTS PS_ZHRT_TRMRS_CREF;
CREATE TABLE PS_ZHRT_TRMRS_CREF (
    ACTION          VARCHAR(3) NOT NULL,
    ACTION_REASON   VARCHAR(3) NOT NULL,
    ZHRF_LEGTERMCD  VARCHAR(1) NOT NULL,
    ZHRF_LEGTERMRSN VARCHAR(1) NOT NULL,
    STATUS          VARCHAR(1) NOT NULL
);
