CREATE TABLE PS_ZHRT_TRMRS_CREF (
    STATUS          NOT NULL VARCHAR2(1 CHAR),
    ACTION          NOT NULL VARCHAR2(3 CHAR),
    ACTION_REASON   NOT NULL VARCHAR2(3 CHAR),
    ZHRF_LEGTERMCD  NOT NULL VARCHAR2(1 CHAR),
    ZHRF_LEGTERMRSN NOT NULL VARCHAR2(1 CHAR)
);