CREATE TABLE PS_ZHRT_CMPNY_CREF (
    STATUS         NOT NULL VARCHAR2(1 CHAR),
    ZHRF_LEGGROUP  NOT NULL VARCHAR2(2 CHAR),
    ZHRF_LEGREGION NOT NULL VARCHAR2(1 CHAR),
    SETID          NOT NULL VARCHAR2(5 CHAR),
    BUSINESS_UNIT  NOT NULL VARCHAR2(5 CHAR),
    COMPANY        NOT NULL VARCHAR2(3 CHAR)
);