CREATE TABLE PS_ETHNIC_GRP_TBL (
    SETID           NOT NULL VARCHAR2(5 CHAR),
    ETHNIC_GRP_CD   NOT NULL VARCHAR2(8 CHAR),
    EFFDT           NOT NULL DATE,
    EFF_STATUS      NOT NULL VARCHAR2(1 CHAR),
    DESCR50         NOT NULL VARCHAR2(50 CHAR),
    DESCRSHORT      NOT NULL VARCHAR2(10 CHAR),
    ETHNIC_CATEGORY NOT NULL VARCHAR2(1 CHAR),
    ETHNIC_GROUP    NOT NULL VARCHAR2(1 CHAR)
);