CREATE TABLE PS_CITIZENSHIP (
    EMPLID             NOT NULL VARCHAR2(11 CHAR),
    DEPENDENT_ID       NOT NULL VARCHAR2(2 CHAR),
    COUNTRY            NOT NULL VARCHAR2(3 CHAR),
    CITIZENSHIP_STATUS NOT NULL VARCHAR2(1 CHAR),
    WORKER_TYPE_SGP    NOT NULL VARCHAR2(1 CHAR),
    PERM_STATUS_DT_SGP          DATE
);
