CREATE TABLE PS_PERS_DATA_EFFDT (
    EMPLID           NOT NULL VARCHAR2(11 CHAR),
    EFFDT            NOT NULL DATE,
    MAR_STATUS       NOT NULL VARCHAR2(1 CHAR),
    MAR_STATUS_DT             DATE,
    SEX              NOT NULL VARCHAR2(1 CHAR),
    HIGHEST_EDUC_LVL NOT NULL VARCHAR2(2 CHAR),
    FT_STUDENT       NOT NULL VARCHAR2(1 CHAR),
    LANG_CD          NOT NULL VARCHAR2(3 CHAR),
    ALTER_EMPLID     NOT NULL VARCHAR2(11 CHAR),
    LASTUPDDTTM               TIMESTAMP(6),
    LASTUPDOPRID     NOT NULL VARCHAR2(30 CHAR)
    );