CREATE TABLE PS_ZHRT_JOBCD_CREF (
    SETID_JOBCODE      NOT NULL VARCHAR2(5 CHAR),
    JOBCODE            NOT NULL VARCHAR2(6 CHAR),
    EMPL_CLASS         NOT NULL VARCHAR2(3 CHAR),
    FULL_PART_TIME     NOT NULL VARCHAR2(1 CHAR),
    REG_TEMP           NOT NULL VARCHAR2(1 CHAR),
    DEPARTMENT         NOT NULL VARCHAR2(10 CHAR),
    STATUS             NOT NULL VARCHAR2(1 CHAR),
    ZHRF_LEGCATEGORYCD NOT NULL VARCHAR2(5 CHAR),
    ZHRF_LEGDEPTCD     NOT NULL VARCHAR2(5 CHAR),
    ZHRF_LEGPOSITIONCD NOT NULL VARCHAR2(5 CHAR),
    ZHRF_LEGJOBSTSCD   NOT NULL VARCHAR2(5 CHAR),
    ZHRF_LEGLEVEL      NOT NULL VARCHAR2(5 CHAR)
);