CREATE TABLE PS_ZHRT_INTTRIGGER (
    SEQ_NBR   NOT NULL NUMBER(15),
    OPRID     NOT NULL VARCHAR2(30 CHAR),
    EMPLID    NOT NULL VARCHAR2(11 CHAR),
    EFFDT              DATE,
    EFFSEQ    NOT NULL NUMBER(38),
    PROC_NAME NOT NULL VARCHAR2(10 CHAR),
    TASK_FLAG NOT NULL VARCHAR2(1 CHAR)
);

