CREATE TABLE PS_PERSONAL_PHONE (
    EMPLID          NOT NULL VARCHAR2(11 CHAR),
    PHONE_TYPE      NOT NULL VARCHAR2(4 CHAR),
    COUNTRY_CODE    NOT NULL VARCHAR2(3 CHAR),
    PHONE           NOT NULL VARCHAR2(24 CHAR),
    EXTENSION       NOT NULL VARCHAR2(6 CHAR),
    PREF_PHONE_FLAG NOT NULL VARCHAR2(1 CHAR)
);