CREATE TABLE PS_COUNTRY_TBL (
    COUNTRY          NOT NULL VARCHAR2(3 CHAR),
    DESCR            NOT NULL VARCHAR2(30 CHAR),
    DESCRSHORT       NOT NULL VARCHAR2(10 CHAR),
    COUNTRY_2CHAR    NOT NULL VARCHAR2(2 CHAR),
    EU_MEMBER_STATE  NOT NULL VARCHAR2(1 CHAR),
    POST_SRCH_AVAIL  NOT NULL VARCHAR2(1 CHAR),
    ADDR_VALIDAT     NOT NULL VARCHAR2(1 CHAR),
    EO_SEC_PAGE_NAME NOT NULL VARCHAR2(18 CHAR)
);
