CREATE TABLE PS_PERSON (
    EMPLID            NOT NULL VARCHAR2(11 CHAR),
    BIRTHDATE         NOT NULL DATE,
    BIRTHPLACE        NOT NULL VARCHAR2(30 CHAR),
    BIRTHCOUNTRY      NOT NULL VARCHAR2(3 CHAR),
    BIRTHSTATE        NOT NULL VARCHAR2(6 CHAR),
    DT_OF_DEATH                DATE,
    LAST_CHILD_UPDDTM          DATE
);