CREATE TABLE PS_HRS_SOURCE_I (
    HRS_SOURCE_ID     NOT NULL NUMBER(15),
    EFFDT             NOT NULL DATE,
    EFF_STATUS                 VARCHAR2(1 CHAR),
    HRS_SOURCE_STATUS          DATE,
    HRS_SOURCE_NAME   NOT NULL VARCHAR2(30 CHAR),
    HRS_SOURCE_DESCR  NOT NULL VARCHAR2(254 CHAR),
    HRS_SOURCE_TYPE   NOT NULL VARCHAR2(3 CHAR)
);