CREATE TABLE PS_DIVERS_ETHNIC (
    EMPLID            NOT NULL VARCHAR2(11 CHAR),
    REG_REGION        NOT NULL VARCHAR2(5 CHAR),
    ETHNIC_GRP_CD     NOT NULL VARCHAR2(8 CHAR),
    SETID             NOT NULL VARCHAR2(5 CHAR),
    APS_EC_NDS_AUS    NOT NULL VARCHAR2(1 CHAR),
    PRIMARY_INDICATOR NOT NULL VARCHAR2(1 CHAR)
);
