CREATE TABLE PS_EMPL_CHECKLIST (
    EMPLID         NOT NULL VARCHAR2(11 CHAR),
    EMPL_RCD       NOT NULL NUMBER(38),
    CHECKLIST_DT   NOT NULL DATE,
    CHECKLIST_CD   NOT NULL VARCHAR2(6 CHAR),
    RESPONSIBLE_ID NOT NULL VARCHAR2(11 CHAR),
    COMMENTS                CLOB
);