CREATE TABLE PSXLATITEM (
    FIELDNAME     NOT NULL VARCHAR2(18 CHAR),
    FIELDVALUE    NOT NULL VARCHAR2(4 CHAR),
    EFFDT                  DATE,
    EFF_STATUS    NOT NULL VARCHAR2(1 CHAR),
    XLATLONGNAME  NOT NULL VARCHAR2(30 CHAR),
    XLATSHORTNAME NOT NULL VARCHAR2(10 CHAR),
    LASTUPDDTTM            TIMESTAMP(6),
    LASTUPDOPRID  NOT NULL VARCHAR2(30 CHAR),
    SYNCID        NOT NULL NUMBER(38)
);
