CREATE TABLE PS_DRIVERS_LIC (
    EMPLID           NOT NULL VARCHAR2(11 CHAR),
    DRIVERS_LIC_NBR  NOT NULL VARCHAR2(20 CHAR),
    STATE            NOT NULL VARCHAR2(6 CHAR),
    COUNTRY          NOT NULL VARCHAR2(3 CHAR),
    VALID_FROM_DT    NOT NULL DATE,
    EXPIRATN_DT               DATE,
    VIOLATIONS       NOT NULL NUMBER(38),
    NUMBER_OF_PTS    NOT NULL NUMBER(38),
    LIC_SUSPENDED_SW NOT NULL VARCHAR2(1 CHAR),
    ISSUED_BY_FRA    NOT NULL VARCHAR2(20 CHAR),
    ISSUE_DEST_FRA   NOT NULL VARCHAR2(20 CHAR),
    COMMENTS                  CLOB
);
