DROP TABLE IF EXISTS PS_ZHRT_JOBCD_CREF;
CREATE TABLE PS_ZHRT_JOBCD_CREF (
    SETID_JOBCODE      VARCHAR(5) NOT NULL PRIMARY KEY,
    JOBCODE            VARCHAR(6) NOT NULL,
    EMPL_CLASS         VARCHAR(3) NOT NULL,
    FULL_PART_TIME     VARCHAR(1) NOT NULL,
    REG_TEMP           VARCHAR(1) NOT NULL,
    DEPARTMENT         VARCHAR(10) NOT NULL,
    STATUS             VARCHAR(1) NOT NULL,
    ZHRF_LEGCATEGORYCD VARCHAR(5) NOT NULL,
    ZHRF_LEGDEPTCD     VARCHAR(5) NOT NULL,
    ZHRF_LEGPOSITIONCD VARCHAR(5) NOT NULL,
    ZHRF_LEGJOBSTSCD   VARCHAR(5) NOT NULL,
    ZHRF_LEGLEVEL      VARCHAR(5) NOT NULL
);
