DROP TABLE IF EXISTS PS_ETHNIC_GRP_TBL;
CREATE TABLE PS_ETHNIC_GRP_TBL (
    SETID           VARCHAR(5) NOT NULL,
    ETHNIC_GRP_CD   VARCHAR(8) NOT NULL,
    EFFDT           DATE NOT NULL,
    EFF_STATUS      VARCHAR(1) NOT NULL,
    DESCR50         VARCHAR(50) NOT NULL,
    DESCRSHORT      VARCHAR(10) NOT NULL,
    ETHNIC_CATEGORY VARCHAR(1) NOT NULL,
    ETHNIC_GROUP    VARCHAR(1) NOT NULL
);
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','UNKWN',STR_TO_DATE('01-JAN-16','%d-%b-%y'),'A','Unknown','Unknown',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','AMIND',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','American Indian/Alaska Native','Am. Ind',' ','5');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','ASIAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Asian','Asian',' ','4');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','BLACK',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Black/African American','Black',' ','2');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','HISPA',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Hispanic/Latino','Hispanic',' ','3');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','NSPEC',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'I','Not Specified','Not Specif',' ','6');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','PACIF',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Native Hawaiian/Other Pacific Islander','Hawaii/Pac',' ','7');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('USA','WHITE',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','White','White',' ','1');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','ACHANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Achang','Achang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','BAI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Bai','Bai',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','BLANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Blang','Blang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','BONAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Bonan','Bonan',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','BOUYEI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Bouyei','Bouyei',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','CHOSEN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Chosen (Korean)','Chosen',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DAI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Dai','Dai',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DAUR',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Daur','Daur',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DEANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Deang','Deang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DONG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Dong','Dong',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DONGXIAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Dongxiang','Dongxiang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','DRUNG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Drung','Drung',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','EWENKI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Ewenki','Ewenki',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','GAOSHAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Gaoshan','Gaoshan',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','GELAO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Gelao','Gelao',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','HAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Han','Han',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','HANI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Hani','Hani',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','HEZHEN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Hezhen','Hezhen',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','HUI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Hui','Hui',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','JING',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Jing','Jing',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','JINGPO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Jingpo','Jingpo',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','JINO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Jino','Jino',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','KAZAK',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Kazak','Kazak',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','KIRGIZ',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Kirgiz','Kirgiz',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','LAHU',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Lahu','Lahu',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','LHOBA',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Lhoba','Lhoba',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','LI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Li','Li',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','LISU',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Lisu','Lisu',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Man','Man',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MAONAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Maonan','Maonan',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MIAO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Miao','Miao',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MOINBA',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Moinba','Moinba',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MONGOL',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Mongol','Mongol',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','MULAO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Mulao','Mulao',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','NAXI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Naxi','Naxi',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','NU',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Nu','Nu',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','OROQEN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Oroqen','Oroqen',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','OZBEK',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Ozbek','Ozbek',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','PUMI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Pumi','Pumi',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','QIANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Qiang','Qiang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','RUSSIAN',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Russian','Russian',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','SALAR',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Salar','Salar',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','SHE',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','She','She',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','SHUI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Shui','Shui',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','TAJIK',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Tajik','Tajik',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','TATAR',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Tatar','Tatar',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','TU',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Tu','Tu',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','TUJIA',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Tujia','Tujia',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','UYGUR',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Uygur','Uygur',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','VA',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Va','Va',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','XIBE',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Xibe','Xibe',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','YAO',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Yao','Yao',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','YI',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Yi','Yi',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','YUGUR',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Yugur','Yugur',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','ZANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Zang','Zang',' ',' ');
Insert into PS_ETHNIC_GRP_TBL (SETID,ETHNIC_GRP_CD,EFFDT,EFF_STATUS,DESCR50,DESCRSHORT,ETHNIC_CATEGORY,ETHNIC_GROUP) values ('CHN','ZHUANG',STR_TO_DATE('01-JAN-00','%d-%b-%y'),'A','Zhuang','Zhuang',' ',' ');
