DROP TABLE IF EXISTS PS_PERS_NID;
CREATE TABLE PS_PERS_NID (
    EMPLID           VARCHAR(11) NOT NULL,
    COUNTRY          VARCHAR(3) NOT NULL,
    NATIONAL_ID_TYPE VARCHAR(6) NOT NULL,
    NATIONAL_ID      VARCHAR(20) NOT NULL,
    SSN_KEY_FRA      VARCHAR(2) NOT NULL,
    PRIMARY_NID      VARCHAR(1) NOT NULL,
    TAX_REF_ID_SGP   VARCHAR(1) NOT NULL,
    LASTUPDDTTM      TIMESTAMP NOT NULL,
    LASTUPDOPRID     VARCHAR(30) NOT NULL
);
