DROP TABLE IF EXISTS PS_ZHRT_CMPNY_CREF;
CREATE TABLE PS_ZHRT_CMPNY_CREF (
    SETID          VARCHAR(5) NOT NULL,
    ZHRF_LEGGROUP  VARCHAR(2) NOT NULL,
    ZHRF_LEGREGION VARCHAR(1) NOT NULL,
    BUSINESS_UNIT  VARCHAR(5) NOT NULL,
    COMPANY        VARCHAR(3) NOT NULL,
    STATUS         VARCHAR(1) NOT NULL
);
