DROP TABLE IF EXISTS PS_ZHRT_RFSRC_CREF;
CREATE TABLE PS_ZHRT_RFSRC_CREF (
    ZHRF_LEGRECRUITSRC VARCHAR(1) NOT NULL,
    REFERRAL_SOURCE    VARCHAR(2) NOT NULL,
    STATUS             VARCHAR(1) NOT NULL
);
