DROP TABLE IF EXISTS PS_EMPL_CHECKLIST;
CREATE TABLE PS_EMPL_CHECKLIST (
    EMPLID         VARCHAR(11) NOT NULL PRIMARY KEY,
    EMPL_RCD       DECIMAL(38,0) NOT NULL,
    CHECKLIST_DT   DATE NOT NULL,
    CHECKLIST_CD   VARCHAR(6) NOT NULL,
    RESPONSIBLE_ID VARCHAR(11) NOT NULL,
    COMMENTS       BLOB
);
