DROP TABLE IF EXISTS PS_ZPTT_VARIABLES;
CREATE TABLE PS_ZPTT_VARIABLES (
    PRCSNAME          VARCHAR(12) NOT NULL,
    DBNAME            VARCHAR(8) NOT NULL,
    VARIABLE_NAME     VARCHAR(15) NOT NULL,
    ZPTF_VARIABLE_VAL VARCHAR(100) NOT NULL,
    LASTUPDOPRID      VARCHAR(30) NOT NULL,
    LASTUPDDTTM       TIMESTAMP
);
