DROP TABLE IF EXISTS PS_ZHRT_ETHCD_CREF;
CREATE TABLE PS_ZHRT_ETHCD_CREF (
    ZHRF_LEGETHNICCD VARCHAR(1) NOT NULL,
    ETHNIC_GROUP     VARCHAR(1) NOT NULL,
    STATUS           VARCHAR(1) NOT NULL
);