DROP TABLE IF EXISTS PS_HRS_SOURCE_I;
CREATE TABLE PS_HRS_SOURCE_I (
    HRS_SOURCE_ID     DECIMAL(15,0) PRIMARY KEY,
    EFFDT             DATE NOT NULL,
    EFF_STATUS        VARCHAR(1),
    HRS_SOURCE_STATUS DATE,
    HRS_SOURCE_NAME   VARCHAR(30) NOT NULL,
    HRS_SOURCE_DESCR  VARCHAR(254) NOT NULL,
    HRS_SOURCE_TYPE   VARCHAR(3) NOT NULL
);
