DROP TABLE IF EXISTS PS_CITIZENSHIP;
CREATE TABLE PS_CITIZENSHIP (
    EMPLID             VARCHAR(11) NOT NULL PRIMARY KEY,
    DEPENDENT_ID       VARCHAR(2) NOT NULL,
    COUNTRY            VARCHAR(3) NOT NULL,
    CITIZENSHIP_STATUS VARCHAR(1) NOT NULL,
    WORKER_TYPE_SGP    VARCHAR(1) NOT NULL,
    PERM_STATUS_DT_SGP DATE
);
