DROP TABLE IF EXISTS PS_EMPLOYEE_REVIEW;
CREATE TABLE PS_EMPLOYEE_REVIEW (
    EMPLID            VARCHAR(11) NOT NULL PRIMARY KEY,
    EMPL_RCD          DECIMAL(38,0) NOT NULL,
    NEXT_REVIEW_DT    DATE NOT NULL,
    EFFDT             DATE NOT NULL,
    REVIEW_FROM_DT    DATE,
    REVIEW_THRU_DT    DATE,
    REVIEW_TYPE       VARCHAR(1) NOT NULL,
    RATING_SCALE      VARCHAR(4) NOT NULL,
    REVIEW_RATING     VARCHAR(1) NOT NULL,
    TOTAL_EE_AMOUNT   DECIMAL(18,6) NOT NULL,
    TOTAL_EE_PERCENT  DECIMAL(5,2) NOT NULL,
    TOTAL_EE_POINTS   DECIMAL(38,0) NOT NULL,
    TOTAL_EE_SAL_PTS  DECIMAL(38,0) NOT NULL,
    EMPL_REVW_STATUS  VARCHAR(1) NOT NULL,
    LOADED_TO_JOB     VARCHAR(1) NOT NULL,
    RES_RVW_BAND_CD   VARCHAR(1) NOT NULL,
    FINAL_RVW_BAND_CD VARCHAR(1) NOT NULL,
    GB_GROUP_ID       VARCHAR(15) NOT NULL,
    GVT_OPM_RATING    VARCHAR(1) NOT NULL,
    FP_REV_RATING     DECIMAL(5,2) NOT NULL,
    LAST_UPDATE_DATE  DATE
);
