Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A',' ',' ');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','A','1');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','B','2');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','C','3');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','D','4');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','E','5');
Insert into PS_ZHRT_ETHCD_CREF (STATUS,ZHRF_LEGETHNICCD,ETHNIC_GROUP) values ('A','O','O');
