DROP TABLE IF EXISTS PS_ETHNIC_GRP_TBL;
CREATE TABLE PS_ETHNIC_GRP_TBL (
    SETID           VARCHAR(5) NOT NULL,
    ETHNIC_GRP_CD   VARCHAR(8) NOT NULL,
    EFFDT           DATE NOT NULL,
    EFF_STATUS      VARCHAR(1) NOT NULL,
    DESCR50         VARCHAR(50) NOT NULL,
    DESCRSHORT      VARCHAR(10) NOT NULL,
    ETHNIC_CATEGORY VARCHAR(1) NOT NULL,
    ETHNIC_GROUP    VARCHAR(1) NOT NULL
);
