DROP TABLE IF EXISTS PS_PERS_APPL_REF;
CREATE TABLE PS_PERS_APPL_REF (
    EMPLID             VARCHAR(11) NOT NULL PRIMARY KEY,
    EFFDT              DATE NOT NULL,
    HRS_SOURCE_ID      DECIMAL(15,0) NOT NULL,
    HRS_SUBSOURCE_ID   DECIMAL(15,0) NOT NULL,
    SPECIFIC_REFER_SRC VARCHAR(50) NOT NULL,
    EMPL_REFERRAL_ID   VARCHAR(11) NOT NULL,
    HRS_PERSON_ID      DECIMAL(15,0) NOT NULL,
    HRS_PROFILE_SEQ    DECIMAL(38,0) NOT NULL,
    PREV_EMPL_BY_COMPY VARCHAR(1) NOT NULL,
    APP_IS_FAMILY      VARCHAR(1) NOT NULL,
    RESUME_TEXT_FILE   VARCHAR(64)
);